global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: /metrics
    static_configs:
      - targets: ['fastapi:8000']  # nom du service FastAPI dans docker-compose

  - job_name: "airflow"
    metrics_path: /metrics
    static_configs:
      - targets: ["airflow-webserver:8080"]

  # Connect to Airflow metrics exporter    
  - job_name: 'airflow'
    metrics_path: /metrics
    static_configs:
      - targets: ['airflow-exporter:9112']

  - job_name: 'mlflow_train'
    metrics_path: /metrics
    static_configs:
      - targets: ['mlflow_exporter_train:9100']

  - job_name: 'mlflow_eval'
    metrics_path: /metrics
    static_configs:
      - targets: ['mlflow_exporter_eval:9101']
