name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker images
        run: |
          docker compose build

      - name: Login to Docker Hub
        if: env.DOCKERHUB_USERNAME != ''
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker images
        if: env.DOCKERHUB_USERNAME != ''
        run: docker compose push

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          password: ${{ secrets.AZURE_PASSWORD }}
          script: |
            cd /home/${{ secrets.AZURE_USER }}/Customer_Churn || git clone https://github.com/PappaLaity/Customer_Churn.git Customer_Churn
            cd Customer_Churn
            git pull origin main
            # --- CREATE .ENV FILE ---
            cat <<EOF > .env
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            MLFLOW_DB_USER=${{ secrets.MLFLOW_DB_USER }}
            MLFLOW_DB_PASSWORD=${{ secrets.MLFLOW_DB_PASSWORD }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            API_KEY_SECRET=${{ secrets.API_KEY_SECRET }}
            GF_SECURITY_ADMIN_USER=${{ secrets.GF_SECURITY_ADMIN_USER }}
            GF_SECURITY_ADMIN_PASSWORD=${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}
            EOF
            # ------------------------
            docker compose down
            docker compose pull || true
            docker compose build
            docker compose up -d
            docker system prune -af